### ISSUE TITLE
克隆到本地后项目无法跑起来，报错

### ISSUE THREAD

**Issue by fenfeiyunluo** [advsets/vue-multi-page#1]
Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-cEmJ9wfQpnZLR35+jGeZk1WmknBbXo0CyiXREeJHUGo='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by epver** [comment]
这个是我在mac上写的一个demo, 今天早上我在公司的windows上试了下,也是可以打开运行的.

你可以把具体报错的截图我看下吗
