### ISSUE TITLE
更好的构建多页面应用

### ISSUE THREAD

**Issue by dengdan99** [advsets/vue-multi-page#3]
hi， 有没有方式更好的构建多页面引用
如果只修改了这些多页面中的一个，能否指打包里面的其中一个呢
如： npm run build page1
我尝试了一下，好像不容易，非要修改 vue-cli-service
请问有什么更好思路吗 谢谢

**Comment by epver** [comment]
这个需要添加 vue-cli 的插件，进行独立构建，目前官方没有支持，由于业务没有需求没有编写的
